### ISSUE TITLE
add docker hub creds

### ISSUE THREAD

**Issue by 0atman** [alphagov/cyber-security-nessus#59]
#58 merged in, flying it now.

```yaml
λ fly set-pipeline -t re -c concourse/pipeline.yml -p nessus
resource types:
  resource type http-api has changed:
  name: http-api
  source:
+   password: ((docker_hub_password))
    repository: gdscyber/http-api-resource
+   username: ((docker_hub_username))
  type: docker-image
  
jobs:
  job nessus_deploy has changed:
  name: nessus_deploy
  plan:
  - get: cyber-security-nessus-git
    passed:
    - terraform_validation
    - python_validation
    trigger: true
  - config:
      image_resource:
        source:
+         password: ((docker_hub_password))
          repository: gdscyber/cyber-security-concourse-base-image
+         username: ((docker_hub_username))
        type: docker-image
      inputs:
      - name: cyber-security-nessus-git
      platform: linux
      run:
        args:
        - -c
        - |
          source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
  
          pip install pipenv
  
          cd cyber-security-nessus-git
  
          pipenv --python 3.7
          pipenv install
  
          make
  
          cd terraform
  
          terraform init
          terraform apply --auto-approve
        path: /bin/bash
    on_failure:
      params:
        health: unhealthy
        message: Failed to deploy nessus.
      put: health-notification
    on_success:
      params:
        health: healthy
        message: Nessus deployed successfully.
      put: health-notification
    task: terraform_deploy
  serial: true
  
  job terraform_validation has changed:
  name: terraform_validation
  plan:
  - get: cyber-security-nessus-git
    trigger: true
  - config:
      image_resource:
        source:
+         password: ((docker_hub_password))
          repository: gdscyber/cyber-security-concourse-base-image
+         username: ((docker_hub_username))
        type: docker-image
      inputs:
      - name: cyber-security-nessus-git
      platform: linux
      run:
        args:
        - -c
        - |
          cd cyber-security-nessus-git
          terraform fmt -diff -check -recursive
        path: bash
    on_failure:
      params:
        health: unhealthy
        message: Failed to validate nessus terraform.
      put: health-notification
    on_success:
      params:
        health: healthy
        message: Nessus terraform validated.
      put: health-notification
    task: run-terraform-fmt
  
  job python_validation has changed:
  name: python_validation
  plan:
  - get: cyber-security-nessus-git
    trigger: true
  - config:
      image_resource:
        source:
+         password: ((docker_hub_password))
          repository: gdscyber/cyber-security-concourse-base-image
+         username: ((docker_hub_username))
        type: docker-image
      inputs:
      - name: cyber-security-nessus-git
      platform: linux
      run:
        args:
        - -c
        - |
          pip install pipenv
          cd cyber-security-nessus-git
          pipenv --python 3.7
          pipenv install --dev
  
          # These are needed to prevent the tests from contacting the AWS magic HTTP server.
          export AWS_ACCESS_KEY_ID=AKIA00AA00AAAA0A0AAA
          export AWS_SECRET_ACCESS_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAA
          export AWS_DEFAULT_REGION=${region:-eu-west-2}
  
          pipenv run pytest
        path: bash
    on_failure:
      params:
        health: unhealthy
        message: Nessus python tests failed
      put: health-notification
    on_success:
      params:
        health: healthy
        message: Nessus python tests passed.
      put: health-notification
    task: run-lambda-validation
  
  job schedule_scans_update has changed:
  name: schedule_scans_update
  plan:
  - get: toml-nessus-git
    trigger: true
  - get: cyber-security-nessus-git
    passed:
    - generate_keys
    trigger: true
  - config:
      image_resource:
        source:
+         password: ((docker_hub_password))
          repository: gdscyber/cyber-security-concourse-base-image
+         username: ((docker_hub_username))
        type: docker-image
      inputs:
      - name: toml-nessus-git
      - name: cyber-security-nessus-git
      platform: linux
      run:
        args:
        - -c
        - |
          cp toml-nessus-git/scan_config/scan.toml cyber-security-nessus-git/scan_config/scan.toml
  
          cd cyber-security-nessus-git
  
          pip install pipenv
          pipenv --python 3.7
          pipenv install
  
          source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
          pipenv run python schedule_scans.py
        path: bash
    on_failure:
      params:
        health: unhealthy
        message: Failed to schedule new scans.
      put: health-notification
    on_success:
      params:
        health: healthy
        message: Nessus has scheduled new scans.
      put: health-notification
    task: update_scheduled_scans
  
  job generate_keys has changed:
  name: generate_keys
  plan:
  - get: cyber-security-nessus-git
    passed:
    - nessus_deploy
    trigger: true
  - config:
      image_resource:
        source:
+         password: ((docker_hub_password))
          repository: gdscyber/cyber-security-concourse-base-image
+         username: ((docker_hub_username))
        type: docker-image
      inputs:
      - name: cyber-security-nessus-git
      platform: linux
      run:
        args:
        - -c
        - |
          pip install pipenv
  
          cd cyber-security-nessus-git
          pipenv --python 3.7
          pipenv install
  
          source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
          cd terraform
          terraform init
          export fqdn=$(terraform output fqdn)
          cd ..
          pipenv run python generate_api_keys.py
        path: /bin/bash
    on_failure:
      params:
        health: unhealthy
        message: Failed to generate nessus API keys.
      put: health-notification
    on_success:
      params:
        health: healthy
        message: API keys generated successfully.
      put: health-notification
    task: generate_api_keys
  serial: true
  
  job Process Scans has changed:
  name: Process Scans
  plan:
  - get: cyber-security-nessus-git
  - get: every-weekday-resource
    trigger: true
  - config:
      image_resource:
        source:
+         password: ((docker_hub_password))
          repository: gdscyber/cyber-security-concourse-base-image
+         username: ((docker_hub_username))
        type: docker-image
      inputs:
      - name: cyber-security-nessus-git
      platform: linux
      run:
        args:
        - -c
        - |
          source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
          pip install pipenv
          cd cyber-security-nessus-git
          pipenv --python 3.7
          pipenv install --dev
          pipenv run python process_scans.py
        path: bash
    on_failure:
      params:
        health: unhealthy
        message: Nessus FAILED to process scans
      put: health-notification
    on_success:
      params:
        health: healthy
        message: Nessus processed scans.
      put: health-notification
    task: process_scans
  

DEPRECATION WARNING:
  - jobs.python_validation: 'python_validation' is not a valid identifier: illegal character '_'
  - jobs.terraform_validation: 'terraform_validation' is not a valid identifier: illegal character '_'
  - jobs.nessus_deploy: 'nessus_deploy' is not a valid identifier: illegal character '_'
  - jobs.nessus_deploy.plan.do[1].task(terraform_deploy): 'terraform_deploy' is not a valid identifier: illegal character '_'
  - jobs.generate_keys: 'generate_keys' is not a valid identifier: illegal character '_'
  - jobs.generate_keys.plan.do[1].task(generate_api_keys): 'generate_api_keys' is not a valid identifier: illegal character '_'
  - jobs.schedule_scans_update: 'schedule_scans_update' is not a valid identifier: illegal character '_'
  - jobs.schedule_scans_update.plan.do[2].task(update_scheduled_scans): 'update_scheduled_scans' is not a valid identifier: illegal character '_'
  - jobs.Process Scans: 'Process Scans' is not a valid identifier: must start with a lowercase letter
  - jobs.Process Scans.plan.do[2].task(process_scans): 'process_scans' is not a valid identifier: illegal character '_'

identifier schema documentation: https://concourse-ci.org/config-basics.html#schema.identifier

apply configuration? [yN]: y
```
